name: Format (PHP)

on:
  push:
    branches:
      - '**'

jobs:
    pint:
        runs-on: ubuntu-latest
        steps:
            - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
              with:
                php-version: '8.1'
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Install
              run: composer install

            - name: Run pint
              run: composer lint

            - uses: EndBug/add-and-commit@v9
              with:
                  message: 'refactor: fix PHP styling'
                  committer_name: github-actions[bot]
                  committer_email: github-actions[bot]@users.noreply.github.com

